### ISSUE TITLE
error catkin build

### ISSUE THREAD

**Issue by arthur-caron** [simonernst/TP_drone#1]
Hello Simon, 

J'ai une erreur à la dernière étape avec le catkin build : 

Traceback (most recent call last):
  File "/usr/bin/catkin", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'osrf-pycommon>0.1.1' distribution was not found and is required by catkin-tools

Est-ce que ça te parle?

**Comment by simonernst** [comment]
Salut, tu es sur quelle version de ROS ?

J'ai l'impression que tu compiles avec Python 3

**Comment by arthur-caron** [comment]
Sur ROS noetic à partir de cette branche : https://github.com/simonernst/iROS_drone/tree/noetic

**Comment by simonernst** [comment]
Tu peux essayer : 
```bash
sudo apt install python3-catkin-lint python3-pip
pip3 install osrf-pycommon
```
ou encore :
```bash
sudo apt install python3-catkin-pkg-modules
sudo apt install python3-rospkg-modules
```

**Comment by arthur-caron** [comment]
merci, les 2 premières lignes n'ont pas marché en revanche avec les 2 suivantes : 
Avec catkin_build j'ai : "catkin_build : commande introuvable"

Mais avec catkin_make en ayant installé libusb-dev j'ai une autre erreur avec glog : 

-- Found OpenCV: /usr (found version "4.2.0") 
CMake Error at iROS_drone/rotors_simulator/rotors_gazebo_plugins/cmake/FindGlog.cmake:77 (MESSAGE):
  Failed to find glog - Could not find glog include directory, set
  GLOG_INCLUDE_DIR to directory containing glog/logging.h
Call Stack (most recent call first):
  iROS_drone/rotors_simulator/rotors_gazebo_plugins/cmake/FindGlog.cmake:103 (GLOG_REPORT_NOT_FOUND)
  iROS_drone/rotors_simulator/rotors_gazebo_plugins/CMakeLists.txt:143 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by simonernst** [comment]
La commande c'est `catkin build` sans le tiret

Pour le problème de glog, as-tu suivi le README de la branche noetic ? [ici](https://github.com/simonernst/iROS_drone/tree/noetic)

**Comment by arthur-caron** [comment]
j'ai supprimé mon ws et refait les consignes du readme c'est bon ça marche ! merci ;)

par contre je ne sais pas pourquoi c'est installé dans /.local/share/Trash/files/bebop_ws.2/bebop_ws/src/bebop_ws

**Comment by simonernst** [comment]
Tant mieux si ça marche, 
par contre, je n'ai aucune idée de pourquoi c'est installé dans un endroit bizarre.
Il n'y a rien dans les dossiers build et devel de ton workspace ?

**Comment by arthur-caron** [comment]
J'ai tout réinstallé maintenant c'est bon, je ne sais pas d'ou venait l'erreur précédente.

Merci pour ton aide :+1:

**Comment by arthur-caron** [comment]
Hello, j'ai refait l'install il faut juste modifier une ligne dans ton readme : 
sudo apt install python3-osrf-pycommon (au lieu de python3-osrf-common)

avec ca tout est parfait :)

**Comment by simonernst** [comment]
Ok je modifie ça, merci !
